name: Code Coverage Summary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18', '20']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
<<<<<<< Updated upstream
          cache: 'npm'
=======
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm
>>>>>>> Stashed changes

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests with Coverage
        run: npm test -- --coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage/**/cobertura-coverage.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-node-${{ matrix.node-version }}
          path: coverage/
