name: Publish to npm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: 'Automated Version Bump'
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag-prefix: 'v'
        skip-tag: 'false'

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
